Add my new source generators
amis92/csharp-source-generators pull request #80
Opened 2022-01-13 14:44 UTC by musictopia2

2022-01-17 22:05 UTC, amis92 commented on README.md
> +- [TxtToListGenerator](https://github.com/musictopia2/TxtToListGenerator)  - A source generator where if you have a text file as additional file and you have a list ordered by return carriages, then
This is not the correct order, should be after Tinyhand.

2022-01-17 22:06 UTC, amis92 requested changes
Please follow the template preceding the list, and add the stars/last-commit badges.

2022-01-17 23:58 UTC, musictopia2 commented
How do I add the stars and last commit badges?  I am guessing if I copied from the previous item, it would show the previous item's stars and last commit which is not accurate.

2022-01-18 20:52 UTC, amis92 commented
There's a template at https://github.com/amis92/csharp-source-generators/blob/06b7d5e59b4f2c00f4c0bec6c5b7d4cf6b57d91b/README.md?plain=1#L20-L23 in which you'd replace `REPO` with `user/repo` part of GitHub URL and append the description. :)

2022-01-18 22:14 UTC, musictopia2 commented
I went ahead and submitted a new pull request.  Because I did not know how to resolve the conflicts without making a backup copy then reforked it.

2022-01-18 22:14 UTC, closed without merging